### PR TITLE
Ft landing page 158429783

### PR DESCRIPTION
**Pull request by JoshuaOndieki**
**What does this PR do?**
Updates the landing page UI.

**Description of Task to be completed?**
The landing page is supposed to look simple and responsive.

**Tasks achieved in this PR**

- [x] Work on the color scheme

- [x] Make the landing page responsive

**How should this be manually tested?**
Clone this repo and test locally on your computer.

**Background Context?**
The UI has no functionality.

**Resources & Libs**
[This Pivotal Tracker board](https://www.pivotaltracker.com/n/projects/2179581) was used to plan and manage the tasks.
[Overview about working with colors in your website](https://www.youtube.com/watch?v=inT-VLzpEzE)

**What are the relevant Pivotal Tracker stories?**
#158483328

**Screenshots**

screencapture-file-home-oj-devel-ridemyway-ui-landingpage-mobile-html-2018-06-20-11_44_29

screencapture-file-home-oj-devel-ridemyway-ui-landingpage-html-2018-06-20-11_47_43

### CODE REVIEW

**Comment by xcixor** [comment]
Looks great and does not lose the feel for the mobile version.

**Comment by ghost** [comment]
Remove the white spaces in between your lines of code

**Comment by artorious** [comment]
Good look on responsiveness
Have you considered giving your `buttons` and form `fieldset` rounded edges for a smoother look?
In CSS, `border-radius` will hook you up

**Comment by Xerrex** [comment]
Nice. Talking as a User would you like make the texts over the image a bit bright ie. white

**Comment by meshack-mbuvi** [comment]
Good design.However, some texts are falling on the dark background which makes them to be invisible mostly on the small devices.

**Pull request merged**
